repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        args: [--target-version, py313]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

# this defines pre-commit hooks to be run locally before each commit
# it includes black for code formatting and flake8 for linting
