[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "odil-wave"
version = "0.1.0"
description = "A package for solving the wave equation using the ODIL framework."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Luke Dinsdale", email = "ld2022@ic.ac.uk" },
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "scikit-image",
    "threadpoolctl",
]

[project.optional-dependencies]
dev = [
    "black>=24.0",
    "flake8>=7.0",
    "pre-commit>=3.0",
    "ipykernel",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

test = [
    "devito",
    "h5py",
    "pytest",
    "pytest-cov",
    "pandas"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["odil_wave*"]

[tool.coverage.run]
source = ["odil_wave"]

[tool.coverage.report]
show_missing = true

[project.scripts]
#odil-wave = "odil_wave.cli:main"
