#!/bin/bash

# utility script to collect all figures presented in the report
# will only work if all result files are collected and stored in
# ../../results/{accuracy,wave,performance}
# see ../jobs/GUIDE.md for more
# ensure relevant dependencies are installed, too

python3 fig1_op_structure.py
python3 fig2_sv_distribution.py 
python3 fig3_plot_models.py 
python3 fig4_accuracy.py
python3 fig5_bare_scaling.py
python3 fig6_hardware_scaling.py
python3 fig7_dispersion.py
python3 fig8_cfl_stability.py
python3 fig9_cfl_snapshot.py
python3 fig10_mode_conv.py