#!/bin/bash
#PBS -N baseline
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=32:mem=32gb:cpu_type=rome

# PBS script for running the baseline model on CX3

set -euo pipefail

module purge
module load tools/prod miniforge/3

# activate env via conda
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate irp

# navigate to working dir
cd $PBS_O_WORKDIR

# install latest package version
pip install .

# run script
python3 scripts/baseline.py --dry