#!/bin/bash
#PBS -N wave-specifics
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32:mem=32gb:cpu_type=rome

# PBS script for running the wave-specific study on CX3
# args:
# OUT=path_to_pkl.pkl

module purge
module load tools/prod miniforge/3

# activate env via conda
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate irp

# navigate to working dir
cd $PBS_O_WORKDIR

# install latest package version
pip install .[test]

OUT=results/wave/wave_specifics.pkl
mkdir -p results/wave

# set thread affinity and location
export OMP_PROC_BIND=close
export OMP_PLACES=cores
export OMP_NUM_THREADS=1 # SuperLU BLAS pinning

python3 experiments/exp3_dispersion.py --out "$OUT"

echo "done -> $OUT"
